
/*
Auto-generated by CVXPYgen on September 11, 2024 at 20:51:33.
Content: Declarations for Python binding with pybind11.
*/

// User-defined parameters
struct CPG_Params_cpp_t {
    std::array<double, 9> Q_w_inv_sqrt;
    std::array<double, 4> Q_v_inv_sqrt;
    std::array<double, 4> Q_u_inv_sqrt;
    std::array<double, 3> x0;
    std::array<double, 9> A;
    std::array<double, 6> B;
    std::array<double, 200> y;
    std::array<double, 6> C;
};

// Flags for updated user-defined parameters
struct CPG_Updated_cpp_t {
    bool Q_w_inv_sqrt;
    bool Q_v_inv_sqrt;
    bool Q_u_inv_sqrt;
    bool x0;
    bool A;
    bool B;
    bool y;
    bool C;
};

// Primal solution
struct CPG_Prim_cpp_t {
    std::array<double, 300> W;
    std::array<double, 200> V;
    std::array<double, 198> U;
    std::array<double, 300> X;
};

// Dual solution
struct CPG_Dual_cpp_t {
    std::array<double, 3> d0;
    std::array<double, 297> d1;
    std::array<double, 200> d2;
    std::array<double, 198> d3;
};

// Solver information
struct CPG_Info_cpp_t {
    double obj_val;
    int iter;
    char* status;
    double pri_res;
    double dua_res;
    double time;
};

// Solution and solver information
struct CPG_Result_cpp_t {
    CPG_Prim_cpp_t prim;
    CPG_Dual_cpp_t dual;
    CPG_Info_cpp_t info;
};

// Main solve function
CPG_Result_cpp_t solve_cpp(struct CPG_Updated_cpp_t& CPG_Updated_cpp, struct CPG_Params_cpp_t& CPG_Params_cpp);
