#ifndef WORKSPACE_H
#define WORKSPACE_H

/*
 * This file was autogenerated by OSQP-Python on September 14, 2024 at 09:41:32.
 * 
 * This file contains the prototypes for all the workspace variables needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#include "types.h"
#include "qdldl_interface.h"

// Data structure prototypes
extern csc Pdata;
extern csc Adata;
extern c_float qdata[1894];
extern c_float ldata[1792];
extern c_float udata[1792];
extern OSQPData data;

// Settings structure prototype
extern OSQPSettings settings;

// Scaling structure prototypes
extern c_float Dscaling[1894];
extern c_float Dinvscaling[1894];
extern c_float Escaling[1792];
extern c_float Einvscaling[1792];
extern OSQPScaling scaling;

// Prototypes for linsys_solver structure
extern csc linsys_solver_L;
extern c_float linsys_solver_Dinv[3686];
extern c_int linsys_solver_P[3686];
extern c_float linsys_solver_bp[3686];
extern c_float linsys_solver_sol[3686];
extern c_float linsys_solver_rho_inv_vec[1792];
extern c_int linsys_solver_Pdiag_idx[698];
extern csc linsys_solver_KKT;
extern c_int linsys_solver_PtoKKT[698];
extern c_int linsys_solver_AtoKKT[6269];
extern c_int linsys_solver_rhotoKKT[1792];
extern QDLDL_float linsys_solver_D[3686];
extern QDLDL_int linsys_solver_etree[3686];
extern QDLDL_int linsys_solver_Lnz[3686];
extern QDLDL_int   linsys_solver_iwork[11058];
extern QDLDL_bool  linsys_solver_bwork[3686];
extern QDLDL_float linsys_solver_fwork[3686];
extern qdldl_solver linsys_solver;

// Prototypes for solution
extern c_float xsolution[1894];
extern c_float ysolution[1792];

extern OSQPSolution solution;

// Prototype for info structure
extern OSQPInfo info;

// Prototypes for the workspace
extern c_float work_rho_vec[1792];
extern c_float work_rho_inv_vec[1792];
extern c_int work_constr_type[1792];
extern c_float work_x[1894];
extern c_float work_y[1792];
extern c_float work_z[1792];
extern c_float work_xz_tilde[3686];
extern c_float work_x_prev[1894];
extern c_float work_z_prev[1792];
extern c_float work_Ax[1792];
extern c_float work_Px[1894];
extern c_float work_Aty[1894];
extern c_float work_delta_y[1792];
extern c_float work_Atdelta_y[1894];
extern c_float work_delta_x[1894];
extern c_float work_Pdelta_x[1894];
extern c_float work_Adelta_x[1792];
extern c_float work_D_temp[1894];
extern c_float work_D_temp_A[1894];
extern c_float work_E_temp[1792];

extern OSQPWorkspace workspace;

#endif // ifndef WORKSPACE_H
