#ifndef WORKSPACE_H
#define WORKSPACE_H

/*
 * This file was autogenerated by OSQP-Python on September 11, 2024 at 21:01:58.
 * 
 * This file contains the prototypes for all the workspace variables needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#include "types.h"
#include "qdldl_interface.h"

// Data structure prototypes
extern csc Pdata;
extern csc Adata;
extern c_float qdata[5494];
extern c_float ldata[4192];
extern c_float udata[4192];
extern OSQPData data;

// Settings structure prototype
extern OSQPSettings settings;

// Scaling structure prototypes
extern c_float Dscaling[5494];
extern c_float Dinvscaling[5494];
extern c_float Escaling[4192];
extern c_float Einvscaling[4192];
extern OSQPScaling scaling;

// Prototypes for linsys_solver structure
extern csc linsys_solver_L;
extern c_float linsys_solver_Dinv[9686];
extern c_int linsys_solver_P[9686];
extern c_float linsys_solver_bp[9686];
extern c_float linsys_solver_sol[9686];
extern c_float linsys_solver_rho_inv_vec[4192];
extern c_int linsys_solver_Pdiag_idx[1898];
extern csc linsys_solver_KKT;
extern c_int linsys_solver_PtoKKT[1898];
extern c_int linsys_solver_AtoKKT[57629];
extern c_int linsys_solver_rhotoKKT[4192];
extern QDLDL_float linsys_solver_D[9686];
extern QDLDL_int linsys_solver_etree[9686];
extern QDLDL_int linsys_solver_Lnz[9686];
extern QDLDL_int   linsys_solver_iwork[29058];
extern QDLDL_bool  linsys_solver_bwork[9686];
extern QDLDL_float linsys_solver_fwork[9686];
extern qdldl_solver linsys_solver;

// Prototypes for solution
extern c_float xsolution[5494];
extern c_float ysolution[4192];

extern OSQPSolution solution;

// Prototype for info structure
extern OSQPInfo info;

// Prototypes for the workspace
extern c_float work_rho_vec[4192];
extern c_float work_rho_inv_vec[4192];
extern c_int work_constr_type[4192];
extern c_float work_x[5494];
extern c_float work_y[4192];
extern c_float work_z[4192];
extern c_float work_xz_tilde[9686];
extern c_float work_x_prev[5494];
extern c_float work_z_prev[4192];
extern c_float work_Ax[4192];
extern c_float work_Px[5494];
extern c_float work_Aty[5494];
extern c_float work_delta_y[4192];
extern c_float work_Atdelta_y[5494];
extern c_float work_delta_x[5494];
extern c_float work_Pdelta_x[5494];
extern c_float work_Adelta_x[4192];
extern c_float work_D_temp[5494];
extern c_float work_D_temp_A[5494];
extern c_float work_E_temp[4192];

extern OSQPWorkspace workspace;

#endif // ifndef WORKSPACE_H
